package ru.voicereminder.app.reminders;
import android.app.*;import android.content.*;import android.os.*;import android.media.*;import android.speech.tts.*;import androidx.core.app.NotificationCompat;import java.util.*;import org.json.*;import ru.voicereminder.app.*;
public class DeliveryService extends Service {
 private TextToSpeech tts;private boolean ready;private JSONObject current;private final Queue<JSONObject> queue=new ArrayDeque<>();private final Handler handler=new Handler(Looper.getMainLooper());private PowerManager.WakeLock lock;private static DeliveryService instance;private AudioManager audio;private AudioFocusRequest focus;
 public static void stopEvent(String id){DeliveryService s=instance;if(s!=null)s.handler.post(()->{s.queue.removeIf(e->e.optString("id").equals(id));if(s.current!=null&&s.current.optString("id").equals(id)){if(s.tts!=null)s.tts.stop();s.finish();}});}
 public static Notification notification(Context c,JSONObject event,JSONObject settings,boolean foreground){NotificationManager nm=c.getSystemService(NotificationManager.class);String channel="raminde_"+(settings.optBoolean("sound",true)&&!foreground?"sound":"silent")+(settings.optBoolean("vibration",true)?"_v":"_n");if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(channel,"Напоминания",NotificationManager.IMPORTANCE_HIGH);ch.enableVibration(settings.optBoolean("vibration",true));if(!settings.optBoolean("sound",true)||foreground)ch.setSound(null,null);nm.createNotificationChannel(ch);}
 Intent open=new Intent(c,MainActivity.class).setFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_SINGLE_TOP);PendingIntent content=PendingIntent.getActivity(c,0,open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);
 String id=event.optString("id"),text=settings.optBoolean("privateNotification")?"Откройте приложение, чтобы посмотреть напоминание":event.optString("text","Напоминание");
 return new NotificationCompat.Builder(c,channel).setSmallIcon(ru.voicereminder.app.R.drawable.ic_reminder).setContentTitle("Remind me").setContentText(text).setStyle(new NotificationCompat.BigTextStyle().bigText(text)).setCategory(NotificationCompat.CATEGORY_ALARM).setPriority(NotificationCompat.PRIORITY_HIGH).setContentIntent(content).setVisibility(settings.optBoolean("privateNotification")?NotificationCompat.VISIBILITY_PRIVATE:NotificationCompat.VISIBILITY_PUBLIC).setOnlyAlertOnce(foreground).setAutoCancel(false).setOngoing(foreground).addAction(0,"Понятно",AlarmScheduler.pending(c,AlarmScheduler.ACK,id)).addAction(0,"Через 5 минут",AlarmScheduler.pending(c,AlarmScheduler.SNOOZE,id)).build();}
 public static void notifyEvent(Context c,JSONObject event,JSONObject settings,boolean foreground){try{c.getSystemService(NotificationManager.class).notify(10000+event.optInt("nativeId"),notification(c,event,settings,foreground));}catch(SecurityException ignored){}}
 @Override public void onCreate(){super.onCreate();instance=this;audio=getSystemService(AudioManager.class);tts=new TextToSpeech(this,status->{ready=status==TextToSpeech.SUCCESS;if(ready){tts.setLanguage(new Locale("ru","RU"));drain();}else{try(ReminderStore db=new ReminderStore(this)){db.diagnostic("TTS недоступен. Проверьте системный голос.");}stopSelf();}});tts.setOnUtteranceProgressListener(new UtteranceProgressListener(){public void onStart(String id){}public void onDone(String id){handler.post(()->finish());}public void onError(String id){handler.post(()->{try(ReminderStore db=new ReminderStore(DeliveryService.this)){db.diagnostic("Не удалось озвучить напоминание: проверьте TTS-голос");}finish();});}});lock=((PowerManager)getSystemService(POWER_SERVICE)).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"raminde:voice");}
 @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent==null){stopSelf();return START_NOT_STICKY;}try(ReminderStore db=new ReminderStore(this)){JSONObject e=db.event(intent.getStringExtra("eventId"));if(e==null){stopSelf();return START_NOT_STICKY;}startForeground(10000+e.optInt("nativeId"),notification(this,e,db.meta("settings"),true));queue.add(e);drain();}return START_NOT_STICKY;}
 private void drain(){if(current!=null||queue.isEmpty()||!ready)return;current=queue.remove();try(ReminderStore db=new ReminderStore(this)){JSONObject e=db.event(current.getString("id"));if(e==null||e.optString("state").equals("acknowledged")||e.optString("state").equals("snoozed")){finish();return;}JSONObject settings=db.meta("settings");NotificationManager nm=getSystemService(NotificationManager.class);if(nm.getCurrentInterruptionFilter()==NotificationManager.INTERRUPTION_FILTER_NONE||audio.getMode()!=AudioManager.MODE_NORMAL){db.diagnostic("Озвучивание пропущено: включён режим «Не беспокоить»");finish();return;}
 if(!lock.isHeld())lock.acquire(30000);AudioAttributes attrs=new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_ALARM).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build();tts.setAudioAttributes(attrs);tts.setSpeechRate((float)settings.optDouble("rate",0.95));if(Build.VERSION.SDK_INT>=26){focus=new AudioFocusRequest.Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK).setAudioAttributes(attrs).setOnAudioFocusChangeListener(change->{if(change==AudioManager.AUDIOFOCUS_LOSS){tts.stop();finish();}}).build();if(audio.requestAudioFocus(focus)!=AudioManager.AUDIOFOCUS_REQUEST_GRANTED){db.diagnostic("Аудио занято другим приложением");finish();return;}}
 String name=settings.optString("name").trim(),text=(name.isEmpty()?"":name+"! ")+current.getString("text");int result=tts.speak(text,TextToSpeech.QUEUE_FLUSH,null,current.getString("id"));if(result==TextToSpeech.ERROR){db.diagnostic("TTS недоступен");finish();return;}handler.postDelayed(watchdog,30000);
 }catch(Exception ex){finish();}}
 private final Runnable watchdog=()->{if(tts!=null)tts.stop();finish();};
 private void finish(){handler.removeCallbacks(watchdog);if(current!=null){try(ReminderStore db=new ReminderStore(this)){JSONObject e=db.event(current.optString("id"));if(e!=null&&e.optString("state").equals("ringing")){e.put("state","waiting");db.put("events","eid",e.getString("id"),e);}JSONObject settings=db.meta("settings");if(e!=null&&settings.optString("mode","voiceAndNotification").equals("voiceAndNotification")&&!e.optString("state").equals("acknowledged"))notifyEvent(this,e,settings,true);}catch(Exception ignored){}}
 if(lock!=null&&lock.isHeld())lock.release();if(Build.VERSION.SDK_INT>=26&&focus!=null)audio.abandonAudioFocusRequest(focus);current=null;if(queue.isEmpty()){stopForeground(STOP_FOREGROUND_DETACH);stopSelf();}else{try(ReminderStore db=new ReminderStore(this)){JSONObject next=queue.peek();startForeground(10000+next.optInt("nativeId"),notification(this,next,db.meta("settings"),true));}drain();}}
 @Override public void onDestroy(){instance=null;handler.removeCallbacksAndMessages(null);if(tts!=null){tts.stop();tts.shutdown();}if(lock!=null&&lock.isHeld())lock.release();if(Build.VERSION.SDK_INT>=26&&focus!=null)audio.abandonAudioFocusRequest(focus);super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
}
